In [1]:
import tensorflow as tf 

In [2]:
#tf.trainable_variable 返回所有可训练的变量
#tf.get_variable,tf.Variable的默认选型是True，而tf.constant是False
a = tf.get_variable('a',shape=[5,2])
b = tf.get_variable('b',shape=[2,5],trainable=False)
c = tf.constant([1,2,3],dtype=tf.int32,shape=[8],name='c')
d = tf.Variable(tf.random_uniform(shape=[3,3]),name='d')

tvar = tf.trainable_variables() 
tvar_name = [x.name for x in tvar]
print(tvar)
print(tvar_name)

[<tf.Variable 'a:0' shape=(5, 2) dtype=float32_ref>, <tf.Variable 'd:0' shape=(3, 3) dtype=float32_ref>]
['a:0', 'd:0']


In [3]:
init = tf.global_variables_initializer() 
sess = tf.Session() 
sess.run(init)
print(sess.run(tvar))

[array([[-0.43024227, -0.29629171],
       [ 0.22535288,  0.82937467],
       [ 0.45182312,  0.77323902],
       [-0.04742885,  0.78847182],
       [-0.28290075, -0.57122117]], dtype=float32), array([[ 0.43129754,  0.93410552,  0.764534  ],
       [ 0.77911818,  0.06108832,  0.10320318],
       [ 0.54089522,  0.50229526,  0.2318418 ]], dtype=float32)]


In [4]:
a1 = tf.get_variable(name='a1',shape=[2,3],initializer=tf.random_normal_initializer(mean=0,stddev=1))
a2 = tf.get_variable(name='a2',shape=[1],initializer=tf.constant_initializer(1))
a3 = tf.get_variable(name='a3',shape=[2,3],initializer=tf.ones_initializer())
init = tf.global_variables_initializer() 
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(a1))
    print(sess.run(a2))
    print(sess.run(a3))
    

[[ 0.64963865  0.10694569 -0.1747442 ]
 [-0.31586263  1.03448629 -1.59911537]]
[ 1.]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]


In [5]:
with tf.name_scope('conv1') as scope:
    weights1 = tf.Variable([1,2],name='weights')
    bias1 = tf.Variable([0.3],name='bias')
    
with tf.name_scope('conv2') as scope:
    weights2 = tf.Variable([4,2],name='weights')
    bias2 = tf.Variable([0.33],name='bias')
    
print(weights1.name)
print(weights2.name)

conv1/weights:0
conv2/weights:0


In [10]:
with tf.variable_scope('conv1') as scope:
    weights1 = tf.Variable([1,2],name='weights')
    bias1 = tf.Variable([0.3],name='bias')
    
with tf.variable_scope('conv1',reuse=True) as scope:
    weights2 = tf.Variable([4,2],name='weights')
    bias2 = tf.Variable([0.33],name='bias')
    
print(weights1.name)
print(weights2.name)

conv1_8/weights:0
conv1_9/weights:0


In [8]:
with tf.variable_scope('conv1') as scope1:
    weights1 = tf.get_variable('weights',shape=[2,3])
    bias1 = tf.get_variable('bias',shape=[3])

with tf.variable_scope('conv1',reuse=True) as scope2:
    weights2 = tf.get_variable('weights')
    
print(weights1.name)
print(weights2.name)

conv1/weights_1:0
conv1/weights_1:0


In [13]:
#在zyy的命名空间内创建名字为v的变量
with tf.variable_scope('zyy'):
    v =tf.get_variable('v',[1],initializer=tf.constant_initializer(1.0))  


In [14]:
#通过tf.get_variable函数创建v的变量，则会失败，由于在zyy空间中已经生成了一个v的变量
with tf.variable_scope('zyy'):
    v = tf.get_variable('v',[1])

ValueError: Variable zyy/v already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2956, in create_op
    op_def=op_def)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)


In [15]:
with tf.variable_scope('zyy',reuse=True):
    v1 = tf.get_variable('v',[1])
    

In [16]:
print(v ==v1)

True


In [30]:
with tf.variable_scope('new_scope',reuse=True):
    an = tf.get_variable('a',shape=[2,5])
b =an 
a_drop = tf.nn.dropout(an,0.8)
init = tf.global_variables_initializer() 
sess = tf.Session() 
sess.run(init)
b_result = sess.run(b)
a_result = sess.run(a_drop)



In [31]:
b_result 

array([[ 0.17171323, -0.89165157,  0.53589201, -0.86983103,  0.17481041],
       [ 0.03753757, -0.03380078,  0.00322402,  0.62648773, -0.06822473]], dtype=float32)

In [32]:
a_result 

array([[ 0.21464154, -1.11456442,  0.66986501, -1.08728874,  0.        ],
       [ 0.04692197, -0.        ,  0.00403002,  0.        , -0.        ]], dtype=float32)