In [10]:
import tensorflow as tf 
import numpy as np 


In [11]:
a = tf.constant([[1,2],[1,2],[1,2]],dtype=tf.float32)
sess = tf.Session() 
result = sess.run(tf.sigmoid(a))
print(result)
#sigmoid函数：S(x) = 1/(1+e-x)
#sigmoid函数的优点在于，它的输出映射在(0,1)内，单调连续，非常适用输出层
#缺点，因为软包和性，一旦输入落入饱和区，f'(x)就会变得接近于0，很容易产生梯度消失



[[ 0.7310586   0.88079703]
 [ 0.7310586   0.88079703]
 [ 0.7310586   0.88079703]]


In [13]:
a = tf.constant([-1,2],dtype=tf.float32)
with tf.Session() as sess:
    b = tf.nn.relu(a)
    print(sess.run(b))

#relu定义为f(x)=max(x,0)
#优点：由于x>0时导数为1，所以relu能够在x>0时保持梯度不衰减，从而解决梯度消失问题，还能够更快收敛
#缺点：x<0时硬饱和。随着训练的进行，部分输入会落到硬饱和区，导致对应的权重无法更新

[ 0.  2.]


In [9]:
result

array([[ 0.7310586 ,  0.88079703],
       [ 0.7310586 ,  0.88079703],
       [ 0.7310586 ,  0.88079703]], dtype=float32)

In [25]:
a = tf.constant([[-1,2,3,4]],dtype=tf.float32)
with tf.Session() as sess:
    b = tf.nn.dropout(a,0.5,noise_shape=[1,4])
    print(sess.run(b))
    b = tf.nn.dropout(a,0.5,noise_shape=[1,1])
    print(sess.run(b))

#dropout函数，一个神经元将以概率keep_prob决定是否被抑制。如果被抑制，该神经元的输出就是0；
#如果不被抑制，那么该神经元的输出值将被放大到原来的1/keep_prob倍


[[-0.  4.  6.  8.]]
[[-0.  0.  0.  0.]]
