In [1]:
import tensorflow as tf 
import numpy as np 

#tf.nn.conv2d(input,filter,strides,padding,use_cudnn_on_gpu=None,data_format=None,name=None)
#这个函数的作用是对一个四维的输入数据input 和四维的卷积核filter进行操作，然后对输入数据进行一个二维的卷积操作，最后得到卷积之后的结果input


In [3]:
input_data = tf.Variable(np.random.rand(10,9,9,3),dtype=np.float32)
filter_data = tf.Variable(np.random.randn(2,2,3,2),dtype=np.float32)
y = tf.nn.conv2d(input_data,filter_data,strides=[1,1,1,1],padding='SAME')



In [4]:
init = tf.global_variables_initializer() 
sess= tf.Session() 
sess.run(init)
print(sess.run(y))

[[[[ -6.66854799e-01  -5.03594208e+00]
   [  3.60906839e-01  -3.78643918e+00]
   [  7.45737553e-02  -1.10549307e+00]
   ..., 
   [  1.75968683e+00  -2.41170645e+00]
   [  5.59043705e-01  -2.83508682e+00]
   [ -2.08456069e-01   1.16307490e-01]]

  [[  1.07813740e+00  -3.27907276e+00]
   [ -6.13066614e-01  -5.50857735e+00]
   [  9.16828811e-01  -1.60699832e+00]
   ..., 
   [  5.90794086e-01  -3.83720493e+00]
   [  5.53795338e-01  -3.22381520e+00]
   [ -1.69775665e+00   6.43593669e-01]]

  [[  3.79135084e+00  -2.76301718e+00]
   [ -5.27330875e-01  -4.23807955e+00]
   [  1.88003767e+00  -2.13153458e+00]
   ..., 
   [  1.91626072e+00  -4.11327934e+00]
   [ -3.66167784e-01  -4.63520670e+00]
   [ -9.54482436e-01   1.40972519e+00]]

  ..., 
  [[  6.14347517e-01  -4.57809734e+00]
   [ -1.28971457e+00  -1.72914433e+00]
   [  1.92903593e-01  -3.87191176e+00]
   ..., 
   [  7.59820580e-01  -4.08702993e+00]
   [  2.20011544e+00  -2.10640717e+00]
   [ -2.45545077e+00   2.14926898e-02]]

  [[ -2.0056

In [5]:
y

<tf.Tensor 'Conv2D_1:0' shape=(10, 9, 9, 2) dtype=float32>